#!/bin/bash
# Script to add inline loading screen to all HTML pages

# The inline loading screen code (minified)
LOADING_SCREEN='<!-- Vision Loading Screen -->
<style>.vision-loader-overlay{position:fixed;top:0;left:0;right:0;bottom:0;background:#0f172a;z-index:9999;display:flex;flex-direction:column;align-items:center;justify-content:center;opacity:1;transition:opacity .4s ease,visibility .4s ease}.vision-loader-overlay.hidden{opacity:0;visibility:hidden;pointer-events:none}.vision-loader-content{display:flex;flex-direction:column;align-items:center;gap:2rem;animation:fadeInUp .6s ease}@keyframes fadeInUp{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}.vision-loader-logo{position:relative;width:120px;height:120px;display:flex;align-items:center;justify-content:center}.vision-loader-logo img{width:80px;height:80px;object-fit:contain;position:relative;z-index:2;animation:logoFloat 2s ease-in-out infinite}@keyframes logoFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}.vision-loader-ring{position:absolute;width:100%;height:100%;border:3px solid transparent;border-top-color:#6366f1;border-right-color:#6366f1;border-radius:50%;animation:spin 1.2s cubic-bezier(.5,0,.5,1) infinite}.vision-loader-ring:nth-child(2){width:90%;height:90%;border-top-color:rgba(99,102,241,.5);border-right-color:rgba(99,102,241,.5);animation-duration:1.5s;animation-direction:reverse}@keyframes spin{0%{transform:rotate(0)}100%{transform:rotate(360deg)}}.vision-loader-title{font-size:1.8rem;font-weight:900;letter-spacing:-.02em;color:#f1f5f9;margin-bottom:.5rem;animation:fadeIn .8s ease .2s both}.vision-loader-subtitle{font-size:.9rem;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.1em;animation:fadeIn .8s ease .4s both}@keyframes fadeIn{from{opacity:0}to{opacity:1}}.vision-loader-bar{width:200px;height:4px;background:rgba(99,102,241,.1);border-radius:2px;overflow:hidden;animation:fadeIn .8s ease .6s both}.vision-loader-bar-fill{height:100%;background:linear-gradient(90deg,#6366f1 0,#8b5cf6 50%,#6366f1 100%);background-size:200% 100%;border-radius:2px;animation:loadingBar 1.5s ease-in-out infinite}@keyframes loadingBar{0%{width:0;background-position:0 0}50%{width:70%;background-position:100% 0}100%{width:100%;background-position:200% 0}}.vision-loader-text{font-size:.85rem;color:#94a3b8;font-weight:500;animation:pulse 1.5s ease-in-out infinite}@keyframes pulse{0%,100%{opacity:.6}50%{opacity:1}}.vision-loader-dots::after{content:"";animation:dots 1.5s steps(4,end) infinite}@keyframes dots{0%,20%{content:""}40%{content:"."}60%{content:".."}80%,100%{content:"..."}}@media (max-width:600px){.vision-loader-logo{width:100px;height:100px}.vision-loader-logo img{width:64px;height:64px}.vision-loader-title{font-size:1.5rem}.vision-loader-subtitle{font-size:.8rem}.vision-loader-bar{width:160px}}[data-theme=light] .vision-loader-overlay{background:#fff}[data-theme=light] .vision-loader-title{color:#1e293b}[data-theme=light] .vision-loader-subtitle{color:#64748b}</style>
<script>(function(){var e='"'"'<div id="visionLoader" class="vision-loader-overlay"><div class="vision-loader-content"><div class="vision-loader-logo"><div class="vision-loader-ring"></div><div class="vision-loader-ring"></div><img src="/assets/logo.png" alt="Vision Education" onerror="this.style.display=\'"'"'none\'"'"'"></div><div style="text-align:center;"><h1 class="vision-loader-title">Vision Education</h1><p class="vision-loader-subtitle">Excellence in Learning</p></div><div class="vision-loader-bar"><div class="vision-loader-bar-fill"></div></div><p class="vision-loader-text">Loading<span class="vision-loader-dots"></span></p></div></div>'"'"';document.body?document.body.insertAdjacentHTML("afterbegin",e):document.addEventListener("DOMContentLoaded",function(){document.body.insertAdjacentHTML("afterbegin",e)});var o=function(){var e=document.getElementById("visionLoader");e&&setTimeout(function(){e.classList.add("hidden"),document.body.style.overflow="",setTimeout(function(){e.parentNode&&e.remove()},400)},800)};"complete"===document.readyState?o():window.addEventListener("load",o),document.body.style.overflow="hidden"})();</script>'

echo "Adding loading screen to HTML files..."
echo "This is a reference script - manual integration recommended"
